config/routes.rb
Rails.application.routes.draw do
  resources :answers
  root 'welcome#index'
  get 'list', to: "answers#list"
end

app/models/answer.rb
class Answer < ActiveRecord::Base
    validates :option, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    def index
      finished = Answer.group(:ip).having('COUNT(*) == 5').count
      @answers = Answer.where('ip IN (?)',  finished.keys)

      @distribution = []
      @questions = []
      
      for i in 0..4
         @distribution[i] = @answers.where("question == ?",i + 1).group(:option).count
         @questions[i] = generate_question(i)
      end
    end
    
    def new
      redirect_to answers_path if answered_questions == 5
      @answer = Answer.new
      @question = generate_question(answered_questions)
    end
    
    def create
      @answer = Answer.new(answer_params)
      @answer.ip = request.remote_ip
      @answer.question = next_question
     
      if @answer.save
        if answered_questions < 5
          @question = generate_question(answered_questions)
          render 'new'
        else
          redirect_to answers_path
        end
      else
        render 'new'
      end
    end
     
    def destroy
      @answer = Answer.find(params[:id])
      @answer.destroy
      redirect_to action: "list"
    end
    
    def list
      @answers = Answer.all
    end
    
    def next_question
      return answered_questions + 1 if answered_questions < 5
      0
    end
    
    def answered_questions
      Answer.where(["ip = ?", request.remote_ip]).length
    end
    
    def generate_question(question)
      questions = [
        {
          'question' => "1) How many books did you read last year?",
          'options' => [
            'none',
            'less than 3',
            'less than 10',
            "10 books or more"
          ]
        },{
          'question' => "2) What book category do you prefere?",
          'options' => [
            'fiction',
            'non-fiction'
          ]
        },{
          'question' => "3) What's your favorite way to read a book?",
          'options' => [
            'paper book',
            'tablet or mobile phone',
            'e-reader',
            'I prefer audio books'
          ]
        },{
          'question' => "4) Usually, how do you choose a book?",
          'options' => [
            "recomendations from friends",
            'best sellers',
            'literary critics',
            "recomendations from specialized apps",
            "by myself"
          ]
        },{
          'question' => '5) How much do you usually pay for a book?',
          'options' => [
            "I don't use to pay for books",
            "less than 5 euros",
            "less than 10 euros",
            "10 euros or more"
          ]
        }
      ]
      
      return questions[question]
    end
    
    private
      def answer_params
        params.require(:answer).permit(:option)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/index.html.erb
<div class="row"> 
  <div class="col-md-offset-3 col-md-6">
    <h1>Quiz - Distribution for Answers</h1>
  </div>
</div>

<% @questions.each_with_index do |question,index| %>
  <div class="row"> 
    <div class="col-md-offset-3 col-md-6">
      <table class="table table-striped table-condensed">
        <caption><%= question["question"] %></caption>
        <tbody>
          <% question["options"].each_with_index do |option,key| %>
            <tr>
              <td><%= option %></td>
              <td><%= @distribution[index][key] ? @distribution[index][key] : 0 %></td>
           </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/answers/list.html.erb
<div class="row"> 
  <div class="col-md-offset-3 col-md-6">
    <h1>Quiz - Distribution for Answers</h1>
  </div>
</div>

<div class="row"> 
  <div class="col-md-offset-3 col-md-6">
    <table class="table table-striped table-condensed">
      <tr>
        <th>ip</th>
        <th>question</th>
        <th>answer</th>
        <th>delete</th>
      </tr>
     
      <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.ip %></td>
          <td><%= answer.question %></td>
          <td><%= answer.option %></td>
          <td><%= link_to 'Destroy', answer_path(answer),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
        <td><%= link_to 'Back', {controller:'answers'}, :class => "btn btn-primary pull-right" %></td>
  </div>
</div>

app/views/answers/new.html.erb
<%= form_for :answer, url: answers_path do |f| %>
<div class="row"> 
  <div class="col-md-offset-3 col-md-6">
    <h1>Quiz - Question</h1>
      <h3><%= @question["question"] %></h3>
    
      <ul class="list-group">
        <% @question["options"].each_with_index do |opt, val| %>
          <li class="list-group-item">
            <%= f.radio_button(:option, val) %>
            <%= f.label(:option_a, opt) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
      <%= f.submit "Next Question", :class => "btn btn-primary pull-right" %>
    </div>
  </div>
<% end %>

app/views/answers/show.html.erb
<p>
  <strong>ip:</strong>
  <%= @answer.ip %>
</p>
 
<p>
  <strong>question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>answer:</strong>
  <%= @answer.option %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz by victorf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width" intitial-scale="1" maximum-scale="1">
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row"> 
  <div class="col-md-offset-3 col-md-6">
    <h1>Quiz by victorf</h1>
    <p>A small tool that does the following:</p>
    
    <ol>
        <li>Shows to a user a simple Quiz, that has 5 questions as 5 separate pages, shown one after another.</li>
        <li>Each question will have 2-5 predefined answers that user can pick from, open answers are not possible.</li>
        <li>After the quiz user should see the results page with answers distribution for each question from all users who completed the quiz (answered all 5 questions).</li>
        <li>The user should not be able to access next question without answering current, or going back to previous questions.</li>
        <li>No login for users should be required.The user should be able to do the quiz only once (We expect that users always use default browser settings and don't use incognito).</li>
    </ol>
  </div>
</div>
<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <%= link_to 'Answer!', {controller: 'answers', action: 'new'}, class: "btn btn-lg btn-success pull-right" %>
    </div>
</div>